### ISSUE TITLE
Shortbow is still not leveling with shooting.

### ISSUE THREAD

**Issue by Keramis** [SlimeKnights/TinkersToolLeveling#127] opened 2022-01-20 06:17 UTC
Modpack: Sky Factory 4
Version of said modpack: 4.2.4

My two arrows are "adept" and "accustomed", due to me using them.
However, my shortbow is still on "clumsy", and has 18xp / 500 (I got 18 xp because I punched some mobs with it)

My friend, who has a crossbow, does have his crossbow leveled up.

Please, can I either have a way to fix this, or an explanation of why this occurs?
![image](https://user-images.githubusercontent.com/81401952/150284139-2cb20814-3646-4326-a42a-db62d48844d6.png)
^ Image for the description of the mod

**Comment by KnightMiner** [comment] 2022-01-31 19:58
Duplicate of #88

**Closed as completed by KnightMiner** 2022-01-31 19:58 UTC
Labels: duplicate
