### ISSUE TITLE
Crossbow XP stays at 0, Doesn't level up

### ISSUE THREAD

**Issue by FalloutBe** [SlimeKnights/TinkersToolLeveling#30] opened 2017-03-07 15:41 UTC
When killing mobs with the crossbow, only the bolts level up, but the crossbow itself stays at 0XP?!

**Comment by KnightMiner** [comment] 2017-03-07 16:19
Duplicate of SlimeKnights/TinkersToolLeveling#19.

**Comment by bonii-xx** [comment] 2017-12-09 15:51
Fixed in newest version

**Closed by bonii-xx** 2017-12-09 15:51 UTC
