### ISSUE TITLE
Update Tinkers' Tool Leveling for v.1.16.5?

### ISSUE THREAD

**Issue by LHDM2000** [SlimeKnights/TinkersToolLeveling#122] opened 2021-04-14 21:21 UTC
Will there be an update for the new version of Tinkers Construct?

**Comment by castilio20** [comment] 2021-04-14 21:30
afaik there is no 1.16 port planned. however you are free to update it if you want.

**Comment by KnightMiner** [comment] 2021-04-14 22:08
Duplicate of #121.

**Closed by KnightMiner** 2021-04-14 22:08 UTC
