### ISSUE TITLE
Can't change item when a modifier is already on there, or item is leveled

### ISSUE THREAD

**Issue by Annon9007723** [SlimeKnights/TinkersToolLeveling#31] opened 2017-03-30 03:20 UTC
I try to add a modifier and that goes all well. But even when it comes to that...I can't figure out how to replace it. I've tried but it said Error, need one or more modifiers (1 more) every time I try replacing a part on my tool.

**Comment by bonii-xx** [comment] 2017-03-31 12:56
You're trying.. to replace a modifier? That's not possible.

**Comment by DoragonKeiyou** [comment] 2017-07-03 19:01
I'm getting the same thing, but the original wording of the issue is a bit weird.  What is being said is that when you swap parts without a modifier on the tool at all, you're fine.  However, if a modifier is present on the tool and you try to swap parts, as shown in my image below, you get an error.  I tested this with a new tool as well to throw out changing config mid play-through and it produces the same result.  The tool provided has 2 modifiers gained from levels, one being used by the obsidian plate.  I have not tested with any other modifiers applied to the tool.

![image](https://user-images.githubusercontent.com/9502203/27805081-12271f84-5ff8-11e7-99b7-0cdda3e10e9a.png)

Not sure if there is a mod conflict or not.  Running both 1.10.2 versions of each mod.

**Comment by DoragonKeiyou** [comment] 2017-12-23 23:58
Update for 1.12.2; issue is still happening.

Config is set to 0 (so they start with 0 modifiers), and if a mod is added to a tool, then the tool can never have a part swapped out cause of the error message.

**Comment by ArticulatedDrunk** [comment] 2018-01-04 01:20
Same problem on my end. I ended up wasting the two other peoples time because I didn't think this could be causing it. I'm running the 1.0.3 version for 1.12

**Comment by bonii-xx** [comment] 2018-05-05 12:52
This actually is a TiC issue, which checks if modifiers are still valid when replacing a toolpart. However to do so it requires free modifiers (it just checks on the new tool, it doesn't actually consume the free modifiers). If it's set to 0, it always fails. I'll see to have this fixed in TiC.

**Closed** 2018-05-05 13:44 UTC
