### ISSUE TITLE
leveling tool

### ISSUE THREAD

**Issue by naze2089** [SlimeKnights/TinkersToolLeveling#81] opened 2018-08-23 11:24 UTC
i won't get any modifiers as i level my tool

**Comment by bonii-xx** [comment] 2018-08-25 16:48
What versions, try reproducing with only TiC, mantle and TTL in a new world.

**Comment by mikolajww** [comment] 2018-09-20 18:09
Is there a command/way to add levels to a tool? I lost my high level tool due to a stupid accident and don't want to start from the beginning.

**Comment by loper12** [comment] 2019-04-14 00:38
probobly an old tool that you had before you installed Tinkers' Tool Leveling. You need to make a new too.

**Comment by Programie** [comment] 2019-05-06 19:09
I have the same issue with the modifiers. I've a Pickaxe on level 7 (Grandmaster) and can't add anymore modifiers. I've currently added a Diamond, Lapis, Redstone and Nether Quartz. Trying to add any other modifier in the tool forge shows "Not enough Modifiers (1 needed)".

**Comment by bonii-xx** [comment] 2019-05-07 17:42
Gonna close this since there never was any further information. @Programie open a new issue when you can reproduce it with a minimal mod set.

**Closed by bonii-xx** 2019-05-07 17:42 UTC

**Comment by Programie** [comment] 2019-05-11 18:01
Just a small update: I've tested it again with a vanilla forge installation + Thinker's Construct + Tinker's Tool Leveling + Mantle (in the same versions as used by my used modpack) and it just works as expected.

After mining a while I was able to add multiple modifiers to my tool (additionally to the basic 3 modifiers). I was able to add diamond, Redstone, Lapis, Nether Quartz, Emerald and Blaze Powder without any issue.

The only difference: I used a Cobalt tool (Cobalt Hammer) instead of a Steel one, because Steel was not available in this combination of mods (I guess Steel is added by another mod). I hope the issue is not caused by using a Steel tool.
