### ISSUE TITLE
Its not working on my server

### ISSUE THREAD

**Issue by RolandRhaine** [SlimeKnights/TinkersToolLeveling#51] opened 2017-11-24 04:07 UTC
So I have never had an issue with this mod before, and I recently got a server for me and a friend to play on and I really wanted this mod. Installed it and it does nothing. There are no levels on my tools or anything. Can someone help? Im used to my single player world where nothing ever goes wrong. I am in way over my head....

**Comment by LoveFireAmi** [comment] 2017-11-24 04:12
Forge version?  Mod version?  Server log?  It is impossible to figure out the issue without more information...

**Comment by RolandRhaine** [comment] 2017-11-24 04:14
Sorry Ive never had to post on any issues for anything before lol Give me on minute i gotta find the server log

**Comment by RolandRhaine** [comment] 2017-11-24 04:17
[latest.log](https://github.com/SlimeKnights/TinkersToolLeveling/files/1500601/latest.log)

As for Forge and Mod version are the newest ones. Forge I just updated to the newest version today and there is only one version of this mod for 1.12.2

**Comment by bonii-xx** [comment] 2017-11-24 11:35
You did put the mod onto both, the server and your local client, right...?

**Comment by RolandRhaine** [comment] 2017-11-24 18:41
yes i did. I even just checked to make sure. And I still cant figure out whats wrong with. Ive never had to activate it or anything in sinleplayer. and it sucks cause i am doing a lot of mining right now. I could really use the extra modifiers.....

**Comment by bonii-xx** [comment] 2017-11-24 19:22
Then you either have it configured improperly or it doesn't load. All I can tell you is that the issue is on your side. Best check the logs if it's loaded and/or errors.

**Comment by RolandRhaine** [comment] 2017-11-24 20:54
IDK how to do any of that. Ive never had this issue before at all.

**Comment by ReverseStateMonad** [comment] 2017-11-26 10:18
Were the tools made before the mod was installed?  I think I recall that existing tools from before adding the mod don't get exp, but if you swap out a part it updates them so that they do.

**Comment by bonii-xx** [comment] 2018-06-02 14:18
Cleanup, closing old tickets.

**Closed by bonii-xx** 2018-06-02 14:18 UTC
