### ISSUE TITLE
XP config changes not reflected ingame

### ISSUE THREAD

**Issue by Lukas45** [SlimeKnights/TinkersToolLeveling#52] opened 2017-12-02 17:37 UTC
If you change the XP requirement of tools, it's not reflected in the ingame tooltip, although it is working.
https://i.gyazo.com/830d13d2b5a79e96c25a95f2f3e370e5.png

The config looks like this:
> "_VERSION"=1*
> general {
>     # Maximum achievable levels. If set to 0 or lower there is no upper limit
>     maximumLevels=-1
>     # Reduces the amount of modifiers a newly build tool gets if the value is lower than the regular amount of modifiers the tool would have
>     newToolMinModifiers=3
> }
> toolxp {
>     # Base XP for each of the listed tools
>     baseXpForTool {
>         "plustic:katana"=200
>         "plustic:laser_gun"=200
>         "tconstruct:arrow"=250
>         "tconstruct:battlesign"=50
>         "tconstruct:bolt"=250
>         "tconstruct:broadsword"=200
>         "tconstruct:cleaver"=300
>         "tconstruct:crossbow"=50
>         "tconstruct:excavator"=500
>         "tconstruct:frypan"=50
>         "tconstruct:hammer"=500
>         "tconstruct:hatchet"=100
>         "tconstruct:longbow"=50
>         "tconstruct:longsword"=200
>         "tconstruct:lumberaxe"=750
>         "tconstruct:mattock"=100
>         "tconstruct:pickaxe"=100
>         "tconstruct:rapier"=150
>         "tconstruct:scythe"=200
>         "tconstruct:shortbow"=50
>         "tconstruct:shovel"=150
>         "tconstruct:shuriken"=100
>     }
>     # Base XP used when no more specific entry is present for the tool
>     defaultBaseXP=200

Modpack: Enigmatica 2 v1.13
MC 1.12.2
Forge .2544
TiC  2.7.4.34
TTL 1.0.2b
Mantle 1.3.1.21

**Comment by GLugia** [comment] 2017-12-03 02:44
I personally tried changing the required xp for each tool and it straight up ignores it and just uses the base value. Not sure what the issue is either. Surprised yours is even working despite the visual bug.

**Comment by bonii-xx** [comment] 2017-12-09 15:50
Fixed in newest version.

**Closed by bonii-xx** 2017-12-09 15:50 UTC
