### ISSUE TITLE
Again cannot change config file with new versions.

### ISSUE THREAD

**Issue by Slowwloriss** [SlimeKnights/TinkersToolLeveling#63] opened 2018-04-14 13:37 UTC
Hi, i saw in changelog that the new version of this mod have a "Config file fix" but with the latest versions of tinker and mantle the issue is back again. 

I donwloaded the files from twitch app, and are the latest for 1.12.2. When i change the config file nothing happens, i tried creating new world, recreating the config file.. nothing, its like the mod doesnt read the config file at all. even the minmodifiers doesnt work. 

- Tinker tool leveling 1.0.3
- tinker construct 2.9.1.65
- Mantle  1.3.2.24
- Forge 2657

**Comment by jerole** [comment] 2018-04-19 10:10
Same problem here, config values are ignored. Using TinkerToolLeveling 1.0.3 with TConstruct 2.9.1.65

**Comment by bonii-xx** [comment] 2018-05-05 12:28
Cannot reproduce, works fine for me. Maybe you don't have proper rights on the file system, or you entered an invalid value?

**Comment by bonii-xx** [comment] 2018-06-02 14:19
Cleanup, closing old tickets.

**Closed by bonii-xx** 2018-06-02 14:19 UTC
